---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role veda_web_frontend
#


veda_web_frontend_service_name: "veda"

veda_web_frontend_user: "{{ veda_web_frontend_service_name }}"
veda_web_frontend_home: "{{ COMMON_APP_DIR }}/{{ veda_web_frontend_service_name }}"

veda_web_frontend_service_home: "{{ COMMON_APP_DIR }}/{{ veda_web_frontend_service_name }}"
veda_web_frontend_code_dir: "{{ veda_web_frontend_service_home }}/{{ veda_web_frontend_service_name }}"
veda_web_frontend_venv_dir: "{{ veda_web_frontend_service_home }}/venvs/{{ veda_web_frontend_service_name }}"

#
# OS packages
#

veda_web_frontend_debian_pkgs:
  - libffi6
  - libffi-dev
  - ffmpeg

VEDA_WEB_FRONTEND_MEMCACHE: []

VEDA_WEB_FRONTEND_DJANGO_SETTINGS_MODULE: "VEDA.settings.production"

VEDA_WEB_FRONTEND_SOCIAL_AUTH_REDIRECT_IS_HTTPS: false

VEDA_WEB_FRONTEND_DATA_DIR: "{{ COMMON_DATA_DIR }}/{{ veda_web_frontend_service_name }}"
VEDA_WEB_FRONTEND_MEDIA_ROOT: "{{ VEDA_WEB_FRONTEND_DATA_DIR }}/media"
VEDA_WEB_FRONTEND_MEDIA_URL: "/media/"

VEDA_WEB_FRONTEND_MEDIA_STORAGE_BACKEND:
  DEFAULT_FILE_STORAGE: "django.core.files.storage.FileSystemStorage"
  MEDIA_ROOT: "{{ VEDA_WEB_FRONTEND_MEDIA_ROOT }}"
  MEDIA_URL: "{{ VEDA_WEB_FRONTEND_MEDIA_URL }}"

VEDA_WEB_FRONTEND_ENVIRONMENT:
  VIDEO_PIPELINE_CFG: "{{ COMMON_CFG_DIR }}/{{ veda_web_frontend_service_name }}.yml"
  PYTHONPATH: "{{ veda_web_frontend_code_dir }}"

VEDA_WEB_FRONTEND_STATICFILES_STORAGE: "django.contrib.staticfiles.storage.StaticFilesStorage"

VEDA_WEB_FRONTEND_GUNICORN_EXTRA: ""

VEDA_WEB_FRONTEND_EXTRA_APPS: []

# See edx_django_service_automated_users for an example of what this should be
VEDA_WEB_FRONTEND_AUTOMATED_USERS: {}
